import React from 'react';
import { Book, ChevronRight, Menu, Circle, CheckCircle2 } from 'lucide-react';
import { TextbookStructure, Chapter, Section } from '../types';

interface SidebarProps {
  structure: TextbookStructure;
  currentChapterId: string;
  currentSectionId: string;
  onSelectSection: (chapter: Chapter, section: Section) => void;
  isOpen: boolean;
  toggleSidebar: () => void;
}

const Sidebar: React.FC<SidebarProps> = ({ 
  structure, 
  currentChapterId, 
  currentSectionId, 
  onSelectSection,
  isOpen,
  toggleSidebar
}) => {
  return (
    <>
      {/* Mobile Overlay */}
      {isOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-20 md:hidden"
          onClick={toggleSidebar}
        />
      )}

      {/* Sidebar Container */}
      <aside 
        className={`
          fixed md:static inset-y-0 left-0 z-30
          w-72 bg-white border-r border-slate-200 
          transform transition-transform duration-300 ease-in-out
          ${isOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}
          flex flex-col
        `}
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-100 flex-shrink-0">
          <div className="flex items-center gap-2 mb-2 text-primary">
            <Book className="w-5 h-5" />
            <span className="font-bold tracking-tight text-sm uppercase">Lumina Textbook</span>
          </div>
          <h1 className="font-serif font-bold text-xl text-slate-900 leading-tight">
            {structure.topic}
          </h1>
          <p className="text-xs text-slate-500 mt-1">For {structure.targetAudience}</p>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-4 space-y-6">
          {structure.chapters.map((chapter) => (
            <div key={chapter.id}>
              <h2 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3 px-2">
                {chapter.title}
              </h2>
              <div className="space-y-1">
                {chapter.sections.map((section) => {
                  const isActive = section.id === currentSectionId;
                  return (
                    <button
                      key={section.id}
                      onClick={() => {
                        onSelectSection(chapter, section);
                        if (window.innerWidth < 768) toggleSidebar();
                      }}
                      className={`
                        w-full text-left px-3 py-2 rounded-md text-sm transition-colors flex items-start gap-3
                        ${isActive 
                          ? 'bg-blue-50 text-primary font-medium' 
                          : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'}
                      `}
                    >
                      <span className="mt-0.5">
                        {isActive ? <CheckCircle2 className="w-4 h-4" /> : <Circle className="w-4 h-4 opacity-20" />}
                      </span>
                      <span className="leading-snug">{section.title}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-100 text-xs text-slate-400 text-center">
          Generated by Gemini 2.5 Flash
        </div>
      </aside>
    </>
  );
};

export default Sidebar;
